name: "GitHub Pull Requests Labeler"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add waiting-for-review label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "pr: waiting for review"
          number: ${{ github.event.pull_request.number }}
